name: Cache Workflow

on:
  push:

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore cache
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-f175c6e

      - name: prime-cache-f175c6e
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" = "true" ]; then
            echo "Cache hit"
          else
            echo "Cache miss"
          fi
